const Fields = [
  "SaleID",
  "PLUItem",
  "GrossAmount",
  "StoreName",
  "UserName",
  "POSSaleType",
  "POSSaleTypeDesc",
  "CategoryName",
  "CategoryID",
  "POSSectionName",
  "TerminalEnteredID",
  "TerminalEnteredName",
  "ClassName",
  "BrandName",
  "TxnHour",
  "PLUCode",
  "TerminalFinalisedName",
  "Amount",
  "BundlePrice",
  "GrossPrice",
  "NetPrice",
  "Sold",
  "HeaderBitMask",
  "ClassID",
  "POSAreaID",
  "LastUpdate",
  "LineID",
  "InputTypeLabel",
  "InputType",
  "UserID",
  "BundleID",
  "PLUID",
  "NetAmount",
  "POSSectionID",
  "POSAreaName",
  "ParentPLUCode",
  "ParentPLUID",
  "Price",
  "HeaderID",
  "TxnTime",
  "SaleTypeID",
  "RealTimeTxn",
  "StoreID",
  "TxnDate",
  "TxnCount",
  "TxnDateTime",
  "TerminalFinalisedID",
  "UTCLastUpdate",
  "TxnFifteenMinute",
  "TxnHalfHour",
  "GST",
];

// const index = Fields.findIndex((e) => e == "TerminalEnteredName");
// console.log(" ---- index ----", index);
console.log(Number("THD1545"))

